
interface SchemaTypes {
    title: string,
    name?: string,
    description: string,
    format?: string,
    type: string,
    pattern?: string,
    message?: any[],
    disabled?: boolean,
    labelWidth?: string,
    readonly?: boolean,
    className?: string,
    width?: string,
    column?: number,
    displayType?: string,
    showDescIcon?: string,
    options?: any[],
    widget?: string,
    minLength?: number,
    maxLength?: number,
    enum?: any[],
    enumNames?: any[],
    required?: boolean,
    url?: string,
    trim?: boolean,
    min?: number,
    max?: number,
    step?: number,
    items?: any,
    minItems?: number,
    maxItems?: number,
    uniqueItems?: boolean,
}